{
 "title": "Raspberry Pi",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Docker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (name) (container_memory_usage_bytes{image!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((time() - container_start_time_seconds{name!=\"\"}) < $__range_s) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Uptime",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{name!=\"\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Live Error Stream",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container!=\"\"} \r\n| logfmt \r\n| level =~ \"error|crit|alert|emerg\" \r\n| line_format \"{{.ts}} 🔴 {{.container}}: {{.msg}}\""
    }
   ]
  },
  { "title": "Raspberry Pi Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Disk Space Used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Disk Write Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"mmcblk0\"}[5m])",
     "legendFormat": "SD Card Write Speed"
    }
   ]
  },
  {
   "title": "Pi Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(node_hwmon_temp_celsius)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pi-hole Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"pihole-FTL.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic (Up/Down)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[5m]) * -1",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}